# Generated by Django 3.2.4 on 2021-06-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_brand_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='address',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='short_description',
        ),
        migrations.AddField(
            model_name='brand',
            name='most_wanted',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
