# Generated by Django 3.2.4 on 2021-06-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20210606_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='code_name',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='address',
        ),
        migrations.AddField(
            model_name='brand',
            name='second_one',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
