from django.contrib import admin
from .models import *

admin.site.site_header = "Hashed System Cloud Commerce"

admin.site.register(Product)
admin.site.register(ProductProperty)
admin.site.register(ProductSpecs)
admin.site.register(Staff)
admin.site.register(Company)
admin.site.register(WareHouse)
admin.site.register(WareHouseStock)
admin.site.register(Category)
admin.site.register(SubCategory)
admin.site.register(SubSubCategory)
admin.site.register(Currency)
admin.site.register(Brand)
admin.site.register(VATCategory)
admin.site.register(ProductType)
admin.site.register(ProductGroup)
admin.site.register(Supplier)
admin.site.register(Csv)
admin.site.register(Admin)
admin.site.register(ProductRelation)
admin.site.register(ProductFinancial)
admin.site.register(Coupon)
admin.site.register(Campaign)
admin.site.register(Customer)
# admin.site.register(Country)
# admin.site.register(City)
admin.site.register(Order)
admin.site.register(OrderDetails)
admin.site.register(Stock)
admin.site.register(OrderReservation)
admin.site.register(Complain)
admin.site.register(ContactUs)
admin.site.register(Wishlist)
admin.site.register(Related)
admin.site.register(Alternative)
admin.site.register(Accessories)
admin.site.register(BoughtTogether)
admin.site.register(LoyaltyPoints)
admin.site.register(EarnedPoints)
admin.site.register(RemainingPoints)
admin.site.register(UsedPoints)
admin.site.register(TrackPoints)
admin.site.register(Author)
admin.site.register(Post)
admin.site.register(PostStatistics)
admin.site.register(Comments)
admin.site.register(PostRelation)
admin.site.register(RelatedPost)
admin.site.register(RelatedItem)
